parameters:
    - name: pool
      type: string
      default: Build
    - name: versionNumber
      type: object
      default:
          major: 1
          minor: 0
          seed: 0

stages:
    - stage: 'Build_Stage'
      displayName: 'Build'

      variables:
          system.debug: false
          buildOutputFolder: 'dist'
          feed: 'CommunicationServicesCUS/G3Npm'
          ##pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store
          pnpm_config_cache: 'C:/Agent-Cache/.pnpm-store'

          major: ${{ parameters.versionNumber.major }}
          minor: ${{ parameters.versionNumber.minor }}
          patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), ${{ parameters.versionNumber.seed }})]
          version: '$(major).$(minor).$(patch)'

      jobs:
          - job: Build_Job

            pool: ${{ parameters.pool }}

            steps:
                - script: |
                      hugo
                  displayName: 'Build Hugo Site'
# # Step 3: Publish the Generated Site as an Artifact (optional)
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: 'public'
#     ArtifactName: 'site'
#   displayName: 'Publish Site Artifact'

# # Step 4: Deploy to an Azure Web App
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '<Your Azure Service Connection>'
#     appName: '<Your Azure Web App Name>'
#     package: '$(System.DefaultWorkingDirectory)/public'
#   displayName: 'Deploy to Azure Web App'
